load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "fusion_lib",
    srcs = [
      "src/fusion_lib/api.c",
      "src/fusion_lib/keyboard/linux/keyboard.c",
      "src/fusion_lib/commands.c",
      "src/fusion_lib/commands.h",
    ],
    hdrs = [
      "src/fusion_lib/api.h",
      "src/fusion_lib/keyboard/keyboard.h",
    ],
    visibility = ["//visibility:public"],
    copts = [
        "-std=c23",
        "-Wall", 
        "-Wextra",
        "-Werror",
        "-Wpedantic",
        "-Wformat=2",
        "-Wconversion", 
        "-Wsign-conversion",
        "-Wshadow",
        "-fstack-protector-strong",
        "-fPIE",
    ],
    target_compatible_with = ["@platforms//os:linux"],
    deps = ["@libusb//:libusb"],
)

cc_binary(
    name = "tui",
    srcs = [
      "src/tui/main.cpp",
      "src/tui/keyboard_service.cpp",
      "src/tui/keyboard_service.h",
      "src/tui/mode_constants.h",
      "src/tui/mode_ui_mapping.cpp",
      "src/tui/mode_ui_mapping.h",
      "src/tui/my_app_component.cpp",
      "src/tui/my_app_component.h",
    ],
    copts = [
        "-std=c++23",
        "-Wall", 
        "-Wextra",
        "-Werror",
        "-Wpedantic",
        "-Wformat=2",
        "-Wconversion", 
        "-Wsign-conversion",
        "-Wshadow",
        "-Wold-style-cast",
        "-Wnon-virtual-dtor",
        "-Woverloaded-virtual",
        "-fstack-protector-strong",
        "-fPIE",
    ],
    target_compatible_with = ["@platforms//os:linux"],
    linkopts = [
        "-pie",
        "-Wl,-z,relro,-z,now",
        "-Wl,-z,noexecstack",
    ],
    deps = ["@ftxui//:component", ":fusion_lib"],
)
